### ISSUE TITLE
Merge Simple Calandar (task calendar) to Etar

### ISSUE THREAD

**Issue by davidhedlund** [xsoh/Etar-Calendar#108]
[Simple Calendar](https://github.com/SimpleMobileTools/Simple-Calendar) can only be used to add Tasks to the calendars, something that Etar lack.

**Comment by jspricke** [comment]
As @tibbi answered already, it doesn't make sense. Btw. Etar is a fork of the original Android calendar, that's why the code base is so old already, although the project is quite young.

Adding task to Etar is already tracked in #83, closing this one.

**Comment by davidhedlund** [comment]
@jsharkey Thanks.
