### ISSUE TITLE
The date is not updated in the widget

### ISSUE THREAD

**Issue by VynceCook** [xsoh/Etar-Calendar#14]
The date is not updated in the widget. The content is scrolled (but late in the day) but
the date on the header of the widget remains the same (in fact it is the date of the day I
added the widget on my screen)

Lolipop 5.0

**Comment by kleisauke** [comment]
@xsoh The main problem of this issue that it is checking if the action "com.android.calendar.APPWIDGET_SCHEDULED_UPDATE" equals with "ws.xsoh.etar.APPWIDGET_SCHEDULED_UPDATE". (At [line 143](https://github.com/xsoh/Etar-Calendar/blob/master/src/com/android/calendar/widget/CalendarAppWidgetProvider.java#L143) in CalendarAppWidgetProvider.java)

This issue can be fixed if you change this:
```java
return context.getPackageName() + ".APPWIDGET_SCHEDULED_UPDATE";
```

At [line 232](https://github.com/xsoh/Etar-Calendar/blob/master/src/com/android/calendar/Utils.java#L232) in Utils.java. To:

```java
return "com.android.calendar.APPWIDGET_SCHEDULED_UPDATE";
```

You may also want to do the same at [line 225](https://github.com/xsoh/Etar-Calendar/blob/master/src/com/android/calendar/Utils.java#L225) and [line 239](https://github.com/xsoh/Etar-Calendar/blob/master/src/com/android/calendar/Utils.java#L239).

**Comment by xsoh** [comment]
@VynceCook Thank you for adding the issue! :+1: 
@kleisauke Thank you for your solution ! :+1:
