### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by miclill** [xsoh/Etar-Calendar#2]
Would be nice to have this in the F-Droid-Repo.
Thank you for your hard work on this project. I really don't get along with the stock calendar.

**Comment by brutus** [comment]
+1 for this.

**Comment by mvdan** [comment]
FYI, we can't build this app because you force Gradle 1.8 - `gradleVersion = '1.8'` - but you use an Android gradle plugin that requires a newer version.

Either specify a newer `gradleVersion` or remove it entirely. And I would set up CI to make it very hard to break the build.

**Comment by xsoh** [comment]
@miclill Thanks for this great suggestion. I'll work on it.
@mvdan Alright, thank you so much.👍👍

I'm AFK these days and I'll do it ASAP. 👍

**Comment by paulle** [comment]
Well done.

**Comment by miclill** [comment]
Wow, thanks. It happened already. First GitHub-Issue that I can close :-)

**Comment by varyoo** [comment]
Just discovered this great app, thanks.

**Comment by fringerdarlinger** [comment]
Just wanted to say thankyou for making this app and making it available to F-Droid. There were no other choices for a calendar app for quite some time.
