### ISSUE TITLE
can not delete weekly shift for Chistmas

### ISSUE THREAD

**Issue by imkarjala** [xsoh/Etar-Calendar#20]
I have my work schedule in my calendar with my Friday shift set to repeat weekly. I want to delete the shift for Fri 25Dec2015, because my employer doesn't want me to work that day. But the calendar only gives the options to either delete or edit that and all following members of the sequence or all members of the sequence. It does not give the option to delete or edit that one member.

**Comment by xsoh** [comment]
Sadly AFAIK the repetition of an event is based on standard that all calendars use and it cannot be customized so you can delete some unless you add them manually. So it cannot be done until it supported from the calendar events it self.

Thank you so much! :+1:
