### ISSUE TITLE
FC when selecting Quick Response tab

### ISSUE THREAD

**Issue by M2ck** [xsoh/Etar-Calendar#22]
Device: Samsung Galaxy S2
ROM: CyanogenMod 12.1 (Android LolliPop 5.1.1)

12-10 19:06:33.270 E/AndroidRuntime(31452): FATAL EXCEPTION: main
12-10 19:06:33.270 E/AndroidRuntime(31452): Process: ws.xsoh.etar, PID: 31452
12-10 19:06:33.270 E/AndroidRuntime(31452): java.lang.RuntimeException: Unable to start activity ComponentInfo{ws.xsoh.etar/com.android.calendar.CalendarSettingsActivity}: java.lang.IllegalArgumentException: Invalid fragment for this activity: com.android.calendar.QuickResponseSettings
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at android.os.Looper.loop(Looper.java:135)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at java.lang.reflect.Method.invoke(Native Method)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at java.lang.reflect.Method.invoke(Method.java:372)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
12-10 19:06:33.270 E/AndroidRuntime(31452): Caused by: java.lang.IllegalArgumentException: Invalid fragment for this activity: com.android.calendar.QuickResponseSettings
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at android.preference.PreferenceActivity.switchToHeaderInner(PreferenceActivity.java:1215)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at android.preference.PreferenceActivity.switchToHeader(PreferenceActivity.java:1241)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:579)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at android.app.Activity.performCreate(Activity.java:5990)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
12-10 19:06:33.270 E/AndroidRuntime(31452): 	... 10 more

**Comment by kleisauke** [comment]
@xsoh Can be fixed if this code: `|| QuickResponseSettings.class.getName().equals(fragmentName)` is added on line 152 in [CalendarSettingsActivity.java](https://github.com/xsoh/Etar-Calendar/blob/master/src/com/android/calendar/CalendarSettingsActivity.java#L152). This will ensures that the [QuickResponseSettings](https://github.com/xsoh/Etar-Calendar/blob/master/src/com/android/calendar/QuickResponseSettings.java) fragment is a valid fragment to be attached to this activity.

**Comment by xsoh** [comment]
@M2ck @kleisauke Thank you guys so much!!
