### ISSUE TITLE
set default calendar for new entry

### ISSUE THREAD

**Issue by zoff99** [xsoh/Etar-Calendar#34]
when creating a new entry with the big red "+" button, and you have many remote calenders set,
it now always chooses some random (?) calender to create the entry in.
for me this is always the wrong one, and i need to manually change it every !! time i create a new entry.

please create a setting or preference to set a default calender to use for new entries.
or at least use the same one, as was chosen for the last entry created!

**Comment by xsoh** [comment]
Fixed :+1:  
Thank you guys !
