### ISSUE TITLE
Cannot import to android studio

### ISSUE THREAD

**Issue by zZVanDucItZz** [xsoh/Etar-Calendar#35]
Hi.
I can't import project into android studio.
can you help me for this?
Thanks!

**Comment by jlafargue** [comment]
It's the same for me! I have problem with the gradle file : 

Error:(123, 0) Basedir /Users/*****/Downloads/Etar-Calendar-master/external/ex/chips does not exist
<a href="openFile:/Users/****/Downloads/Etar-Calendar-master/build.gradle">Open File</a>

**Comment by xsoh** [comment]
@zZVanDucItZz can give me please what happens? it should work with Android studio by default.

@jlafargue please make sure that you have import the submodels before you do the build, here:
https://github.com/xsoh/Etar-Calendar#build-instructions

**Comment by luvyouso** [comment]
File -> new -> Import project
Add : 
 useLibrary 'org.apache.http.legacy'
lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }

on file build.gradle in app.

**Comment by prasanthmurugan** [comment]
I Have the same problem now how to solve it !!!!! @luvyouso i tried your solution but not working for me

**Comment by luvyouso** [comment]
pls @prasanthmurugan check project example of me.
https://github.com/luvyouso/CalendarGoogle2016
