### ISSUE TITLE
Unable find /Etar-Calendar/external/ex/chips

### ISSUE THREAD

**Issue by ruanqin0706** [xsoh/Etar-Calendar#36]
Error:(123, 0) Basedir .../Etar-Calendar/external/ex/chips does not exist
<a href="openFile: .../github/20160318/Etar-Calendar/build.gradle">Open File</a>

**Comment by xsoh** [comment]
You have to get the submodels before you build the gradle file
please see here:
https://github.com/xsoh/Etar-Calendar#build-instructions

**Comment by ruanqin0706** [comment]
Thank you for what you said ! I got it now !!

**Comment by ruanqin0706** [comment]
Thank you for what you said ! I got it now !!

**Comment by xsoh** [comment]
Sure ! enjoy coding :smiley:

**Comment by ruanqin0706** [comment]
Is there any posts about the principle of the app? Because the architecture of this app is different with what I learned before. I still can not understand how to complete it . /(ㄒoㄒ)/~~ 

What I want to know most is that how to complete repeat schedule ? That means I want to know when you create repeat schedule , then how to store it, how to appear it on the ui interface ? Which classes and methods achieve function ?

(Forgive my poor English and hope your answer Sincerely. :-D)

**Comment by xsoh** [comment]
I'm sorry AFAIK there is no documentation for the app :disappointed: 
What I really did is to run the app and do some changes to get the idea "still I don't know all of the feature of the app".

**Comment by HasnaaMohammed** [comment]
where to write these instructions ?
