### ISSUE TITLE
No option to select default calendar.

### ISSUE THREAD

**Issue by einalex** [xsoh/Etar-Calendar#40]
The calendar used to add new appointments to is in my case one that holds birthdays. This is extremely annoying as I have to select the correct calendar every single time Icreate an appointment. 

I would really really appreaciate an option that allows me to select a default calendar.
Alternatively it would help if Etar, upon creating an appointment remembered the choice of calendar and used that as a preset for the next appointment.

**Comment by jspricke** [comment]
This should be fixed in 1.0.3 ;).

**Comment by einalex** [comment]
oh yes yes yes :)
