### ISSUE TITLE
Support Android 6.0.1 / CM13.0? 

### ISSUE THREAD

**Issue by Zeitwaechter** [xsoh/Etar-Calendar#43]
Hey there! 

Still loving your App! 

I'm having a question, though! 
The App can't be started with the above stated fresh installed OS and gApps Pico. 

... 
I know that the reporting feature could help you but it's deactivated OOTB :3

Would it be possible to test it by yourself, though? :D

I wouldn't want to search for another free one :(

Greetings
Zeitwaechter

**Comment by paulle** [comment]
Dear dev,
I like your calendar very much, but I have one issue. I had your calendar installed (via f-droid) running cm12.1.
A week ago I switched to cm13 and tried to use the latest update of ETAR via f-droid (v1.0.3), but it always crashed.
Tried the actual version in playstore (v1.0.2) which is older, but it works with cm13.
Don't know the reason for this issue, but it seems the latest version of Etar is not playing well with cm13.

Thank you for your beautiful calendar, since coming out it's my favorite.

**Comment by zoff99** [comment]
please merge #39 
then CM13 / android M can be tested with automated testing on circleCI

**Comment by zoff99** [comment]
seems to be "Permission Denial"

 `java.lang.SecurityException: Permission Denial: opening provider com.android.providers.calendar.CalendarProvider2 from ProcessRecord{7391872 1912:ws.xsoh.etar/u0a53} (pid=1912, uid=10053) requires android.permission.READ_CALENDAR or android.permission.WRITE_CALENDAR`

see:

https://circle-artifacts.com/gh/zoff99/Etar-Calendar/35/artifacts/0/tmp/circle-artifacts.h4qGmDy/adb_out.txt

**Comment by zoff99** [comment]
http://stackoverflow.com/questions/32635704/android-permission-doesnt-work-even-if-i-have-declared-it

As a temporary workaround, drop your targetSdkVersion below 23

**Comment by zoff99** [comment]
@Zeitwaechter : can you try this version:

https://circle-artifacts.com/gh/zoff99/Etar-Calendar/39/artifacts/0/tmp/circle-artifacts.13oAxHh/etar_circleci_ac12af8ebb2eea5594a6f91a99bd8445166f922c.apk

it is compiled against API22 as a workaround, until there is a better fix.
[!!use at your own risk!!]

**Comment by Zeitwaechter** [comment]
Works just fine! 
Thank you very much, for now ;D

**Comment by jspricke** [comment]
@zoff99 sounds good to me, can you send a pull request with the change?

**Comment by xsoh** [comment]
Thank you guys for work! :+1: 
I'm working now on fix of this critical bug

**Comment by xsoh** [comment]
Done. 
Please refare to this issue if the bug is still exist

**Comment by paulle** [comment]
Hello and thank you,
v1.0.4 works now perfectly with android 6.01 (cm13 unofficial) on my xperia z5. Great work.

**Comment by xsoh** [comment]
@paulle Great to hear, thank you so much ! 👍
