### ISSUE TITLE
Consider renaming/adding "calender" in the title

### ISSUE THREAD

**Issue by rugk** [xsoh/Etar-Calendar#44]
Just for SEO reasons "calender" should be mentioned in the title.

Because when I e.g. search on FDroid for "calender" it does not show up. "Renaming" it to "Etar Calender" would fix this.

**Comment by jspricke** [comment]
It's calendar and searching for it in F-Droid brings up Etar for me ;). If you still think it should be changes, please open an issue wiht the F-Droid people, as it's their metadata.
