### ISSUE TITLE
Does not work without Google calendar account

### ISSUE THREAD

**Issue by rugk** [xsoh/Etar-Calendar#45]
Because I want to use Google Play I have GApps installed. (Smallest package [pico] from OpenGApps)

However as this app interacts with the Android calendar every time when I try to add a new entry it always asks me to sign in to Google to use an (offline! - hopefully) calendar.
Can't you circumvent this stupid login?

Or any other working solution in my situation? (Uninstalling some part of the GApps or so?)

**Comment by zoff99** [comment]
install and use this:

https://f-droid.org/repository/browse/?fdid=org.sufficientlysecure.localcalendar

**Comment by rugk** [comment]
Thanks, what about adding this to the Readme/FAQ/Wiki somewhere?

**Comment by moshpirit** [comment]
Can't use Offline Calendar on my Android 6 device (no Gapps). Probably the best option is leting us to use it locally, without forcing us to use an existent calendar.

**Comment by jspricke** [comment]
Etar is a program to display and edit a calendar, not to store it. If you don't  use the play store, you can get Offline Calendar for example over here: https://f-droid.org/app/org.sufficientlysecure.localcalendar

**Comment by moshpirit** [comment]
Sorry, my bad, i uninstalled the com.android.calendar.providers package
