### ISSUE TITLE
v. 1.0.3 crashes

### ISSUE THREAD

**Issue by iGormilhit** [xsoh/Etar-Calendar#46]
I'm running Cyanogenmod 13.0-20160419-SNAPSHOT... without the GAPPS and Etar v. 1.0.3 from f-droid crashes at start. I've tried to install v. 1.0.2 and so far it works well

Edit : I can add that I using DAVdroid to sync my calendars from OwnCloud.

**Comment by xsoh** [comment]
Please try to use Etar v1.0.4 the bug has been fixed there.

Thanks 👍

**Comment by iGormilhit** [comment]
Everything is ok with v.1.0.4 ! Thanks a lot. :+1:
