### ISSUE TITLE
Upload data manually also.. Need not to sync with other calendars.

### ISSUE THREAD

**Issue by Savinkannan** [xsoh/Etar-Calendar#74]
Maintain an separate local calendar for this app only. And that data should be easily uploaded to calendar views by manually from sqlite (from android local db). Need not to sync with other calendars.

Like: [AgendaCalendarView](https://github.com/Tibolte/AgendaCalendarView)

**Comment by jspricke** [comment]
Etar is a program to display and edit a calendar, not to store it. If you don't use the play store, you can get Offline Calendar for example over here: https://f-droid.org/app/org.sufficientlysecure.localcalendar
