### ISSUE TITLE
Show more events in widget

### ISSUE THREAD

**Issue by Raphi111** [xsoh/Etar-Calendar#79]
Hello and thanks for this great app ! I love it because it doesn't need google play services to work.
I have a question though, would it be possible to show more event in the widget ? I have some incoming events but only one is showing and there is room to display a lot more. Here is a screenshot showing google calendar vs etar: [http://i.imgur.com/NsRBcKU.jpg](http://i.imgur.com/NsRBcKU.jpg)

**Comment by jspricke** [comment]
Hi Raphi,
it shows a lot more events for me. Are they in different calendars and did you probably deselect them in the displayed calendars in the app? An other option is to use the [Calendar Widget](https://f-droid.org/repository/browse/?fdfilter=calendar&fdid=com.plusonelabs.calendar).

**Comment by Raphi111** [comment]
Thank you for your answer, they are on multiple calendars but everyone of them is selected to sync and display. Could it be because they are not in the same week ? I have only one item this week and a lot more next week.
Calendar widget does show a lot more (like google calendar) but I prefer the look and feel of Etar.
Anyway if I don't find a way to solve this I will stick with Calendar widget, thanks :)

**Comment by jspricke** [comment]
Ah, missed that. Yes, afair it only shows the next week.

**Comment by Raphi111** [comment]
Ok :)
Do you think it would be possible to show the next x items or to add a setting to show the whole month ?
Anyway it is not a big issue but I was wondering why it only showed one item, I didn't want to miss an event
