### ISSUE TITLE
android.permission.INTERNET

### ISSUE THREAD

**Issue by jspricke** [xsoh/Etar-Calendar#9]
Hi,

do you really need android.permission.INTERNET in AndroidManifest.xml? A quick grep turned up nothing. Would be great to get rid of it.

Thanks for taking care of the calendar app!

**Comment by xsoh** [comment]
Wow!
I really don't know if there is reason for that!
It seems to be written in the first commit of the project without reason. Anyway, it really need to be double checked before we go on.

Thanks Jochen!

**Comment by xsoh** [comment]
@jspricke Thank you so much!
Done.
